#!/usr/bin/env node
/**
 * Generates supabase/seed.sql from the data literals embedded in index.html.
 *
 * It extracts the GRADIENTS, CITIES and EVENTS array/object literals straight
 * from the source and evaluates just those (in isolation, no DOM needed), so
 * the seed always stays in sync with the app's demo data. Re-run after editing
 * the CITIES/EVENTS arrays:  node scripts/gen-seed.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const html = readFileSync(join(root, 'index.html'), 'utf8');

// Pull out a `const NAME = <literal>;` block by brace/bracket matching.
function extractLiteral(src, name, open, close) {
  const start = src.indexOf(`const ${name} =`);
  if (start === -1) throw new Error(`could not find const ${name}`);
  const from = src.indexOf(open, start);
  let depth = 0, i = from;
  for (; i < src.length; i++) {
    if (src[i] === open) depth++;
    else if (src[i] === close && --depth === 0) { i++; break; }
  }
  return src.slice(from, i);
}

const GRADIENTS = eval('(' + extractLiteral(html, 'GRADIENTS', '{', '}') + ')');
const CITIES = eval('(' + extractLiteral(html, 'CITIES', '[', ']') + ')');
// EVENTS references G (= GRADIENTS); expose it for the eval scope.
const G = GRADIENTS;
const EVENTS = eval('(' + extractLiteral(html, 'EVENTS', '[', ']') + ')');

const q = (v) => v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`;
const num = (v) => v === null || v === undefined || v === '' ? 'null' : Number(v);
const bool = (v) => v ? 'true' : 'false';
const arr = (a) => a && a.length
  ? `array[${a.map(x => q(x)).join(',')}]`
  : "array[]::text[]";

let sql = `-- AUTO-GENERATED by scripts/gen-seed.mjs — do not edit by hand.
-- Seeds the demo cities and events. Safe to re-run (upsert on id).
begin;

`;

for (const c of CITIES) {
  sql += `insert into public.cities (id,name,state,emoji,lat,lng,zoom,tagline,event_count) values (`
    + `${q(c.id)},${q(c.name)},${q(c.state)},${q(c.emoji)},${num(c.lat)},${num(c.lng)},${num(c.zoom)},${q(c.tagline)},${num(c.eventCount)})`
    + ` on conflict (id) do update set name=excluded.name,state=excluded.state,emoji=excluded.emoji,lat=excluded.lat,lng=excluded.lng,zoom=excluded.zoom,tagline=excluded.tagline,event_count=excluded.event_count;\n`;
}
sql += '\n';

for (const e of EVENTS) {
  sql += `insert into public.events (id,city_id,name,type,type_label,venue,neighborhood,date,"time",price,litt_score,rating,reviews,going,lat,lng,vibes,description,emoji,featured,trending,tonight,tier,zip) values (`
    + `${num(e.id)},${q(e.city)},${q(e.name)},${q(e.type)},${q(e.typeLabel)},${q(e.venue)},${q(e.neighborhood)},${q(e.date)},${q(e.time)},${q(e.price)},`
    + `${num(e.littScore)},${num(e.rating)},${num(e.reviews)},${num(e.going)},${num(e.lat)},${num(e.lng)},${arr(e.vibes)},${q(e.description)},${q(e.emoji)},`
    + `${bool(e.featured)},${bool(e.trending)},${bool(e.tonight)},${q(e.tier)},${q(e.zip)})`
    + ` on conflict (id) do update set city_id=excluded.city_id,name=excluded.name,type=excluded.type,type_label=excluded.type_label,venue=excluded.venue,neighborhood=excluded.neighborhood,date=excluded.date,"time"=excluded.time,price=excluded.price,litt_score=excluded.litt_score,rating=excluded.rating,reviews=excluded.reviews,going=excluded.going,lat=excluded.lat,lng=excluded.lng,vibes=excluded.vibes,description=excluded.description,emoji=excluded.emoji,featured=excluded.featured,trending=excluded.trending,tonight=excluded.tonight,tier=excluded.tier,zip=excluded.zip;\n`;
}

// Note: no setval here. Curated events use explicit ids; ingested events use the
// separate events_ext_id_seq (migration_006, starts at 2,000,000), so there's no
// sequence to advance. (events.id is a plain bigint with no owned sequence, so
// pg_get_serial_sequence() returns NULL and setval(NULL,…) would error.)
sql += `\ncommit;\n`;

writeFileSync(join(root, 'supabase', 'seed.sql'), sql);
console.log(`Wrote supabase/seed.sql — ${CITIES.length} cities, ${EVENTS.length} events.`);
